services:
  nllb-service:
    build: .
    container_name: nllb_ar_ru_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      HF_HOME: /app/storage/huggingface
      TRANSFORMERS_CACHE: /app/storage/huggingface
      HF_HUB_CACHE: /app/storage/huggingface
      TRANSFORMERS_OFFLINE: ${NLLB_TRANSFORMERS_OFFLINE:-0}
    volumes:
      - ${STORAGE_PATH}:/app/storage
    networks:
      - shared_net
    restart: unless-stopped

networks:
  shared_net:
    external: true
